"""Export ranked job matches to CSV and Markdown."""

from pathlib import Path

import pandas as pd


DISPLAY_COLUMNS = [
    "match_score",
    "title",
    "company",
    "location",
    "job_type",
    "cluster_label",
    "similarity_score",
    "location_penalty",
    "job_type_penalty",
    "feedback_adjustment",
    "user_feedback",
    "match_reason",
    "profile_skills_found",
    "missing_skills",
    "skill_match_rate",
    "matched_keywords",
    "avoid_keywords_found",
    "notes",
    "link",
]

GOOGLE_SHEETS_COLUMNS = [
    "match_score",
    "user_feedback",
    "notes",
    "title",
    "company",
    "location",
    "job_type",
    "job_cluster",
    "cluster_label",
    "date_found",
    "source",
    "similarity_score",
    "keyword_bonus",
    "location_bonus",
    "location_penalty",
    "role_bonus",
    "job_type_bonus",
    "job_type_penalty",
    "avoid_penalty",
    "feedback_adjustment",
    "match_reason",
    "profile_skills_found",
    "job_skills_found",
    "missing_skills",
    "skill_match_rate",
    "matched_keywords",
    "avoid_keywords_found",
    "link",
]


def export_to_csv(jobs: pd.DataFrame, output_path: Path) -> None:
    """Save the full ranked job table as a CSV file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    jobs.to_csv(output_path, index=False)


def export_google_sheets_ready_csv(jobs: pd.DataFrame, output_path: Path) -> None:
    """Save a clean CSV that is easy to import into Google Sheets.

    This export intentionally excludes internal NLP columns such as clean_text
    and combined_text. The feedback columns are kept near the front so the user
    can update them directly in a spreadsheet.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    columns = [col for col in GOOGLE_SHEETS_COLUMNS if col in jobs.columns]
    sheets_ready_jobs = jobs[columns].copy()
    sheets_ready_jobs.to_csv(output_path, index=False)


def _escape_markdown(value: object) -> str:
    """Escape values so they render correctly inside Markdown tables."""
    text = str(value).replace("\n", " ").strip()
    return text.replace("|", "\\|")


def export_to_markdown(jobs: pd.DataFrame, output_path: Path, top_n: int = 10) -> None:
    """Save the top ranked jobs as a beginner-friendly Markdown report."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    columns = [col for col in DISPLAY_COLUMNS if col in jobs.columns]
    top_jobs = jobs.head(top_n)[columns]

    lines = [
        "# Ranked Career Opportunities",
        "",
        "This report was generated by the Personal Career Opportunity Tracker.",
        "",
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]

    for _, row in top_jobs.iterrows():
        values = [_escape_markdown(row[col]) for col in columns]
        lines.append("| " + " | ".join(values) + " |")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
