"""Export ranked job matches to CSV and Markdown."""

from pathlib import Path

import pandas as pd


DISPLAY_COLUMNS = [
    "match_score",
    "title",
    "company",
    "location",
    "job_type",
    "similarity_score",
    "location_penalty",
    "job_type_penalty",
    "matched_keywords",
    "avoid_keywords_found",
    "link",
]


def export_to_csv(jobs: pd.DataFrame, output_path: Path) -> None:
    """Save the full ranked job table as a CSV file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    jobs.to_csv(output_path, index=False)


def _escape_markdown(value: object) -> str:
    """Escape values so they render correctly inside Markdown tables."""
    text = str(value).replace("\n", " ").strip()
    return text.replace("|", "\\|")


def export_to_markdown(jobs: pd.DataFrame, output_path: Path, top_n: int = 10) -> None:
    """Save the top ranked jobs as a beginner-friendly Markdown report."""
    output_path.parent.mkdir(parents=True, exist_ok=True)

    columns = [col for col in DISPLAY_COLUMNS if col in jobs.columns]
    top_jobs = jobs.head(top_n)[columns]

    lines = [
        "# Ranked Career Opportunities",
        "",
        "This report was generated by the Personal Career Opportunity Tracker.",
        "",
        "| " + " | ".join(columns) + " |",
        "| " + " | ".join(["---"] * len(columns)) + " |",
    ]

    for _, row in top_jobs.iterrows():
        values = [_escape_markdown(row[col]) for col in columns]
        lines.append("| " + " | ".join(values) + " |")

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
